package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	pgx "github.com/jackc/pgx/v5"
	"github.com/jmcintyre/secbase/api/internal/auth"
	model1 "github.com/jmcintyre/secbase/api/internal/graph/model"
	"github.com/jmcintyre/secbase/api/internal/model"
	"github.com/jmcintyre/secbase/api/internal/repository"
)

// BusinessOwner is the resolver for the businessOwner field.
func (r *assetResolver) BusinessOwner(ctx context.Context, obj *model.Asset) (*model.User, error) {
	if obj.BusinessOwnerID == nil {
		return nil, nil
	}
	return r.resolveUser(ctx, *obj.BusinessOwnerID)
}

// TechnicalOwner is the resolver for the technicalOwner field.
func (r *assetResolver) TechnicalOwner(ctx context.Context, obj *model.Asset) (*model.User, error) {
	if obj.TechnicalOwnerID == nil {
		return nil, nil
	}
	return r.resolveUser(ctx, *obj.TechnicalOwnerID)
}

// Vulnerabilities is the resolver for the vulnerabilities field.
func (r *assetResolver) Vulnerabilities(ctx context.Context, obj *model.Asset, first *int, after *string) (*model1.VulnerabilityConnection, error) {
	params := paginationParams(first, after)

	var vulns []*model.Vulnerability
	var pr repository.PaginationResult

	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		vulns, pr, err = r.VulnRepo.ListByAsset(ctx, tx, obj.ID, params)
		return err
	})
	if err != nil {
		return nil, err
	}

	edges := make([]*model1.VulnerabilityEdge, len(vulns))
	for i, v := range vulns {
		edges[i] = &model1.VulnerabilityEdge{
			Cursor: repository.EncodeCursor(i),
			Node:   v,
		}
	}

	return &model1.VulnerabilityConnection{
		Edges:      edges,
		PageInfo:   toPageInfo(pr),
		TotalCount: pr.TotalCount,
	}, nil
}

// Comments is the resolver for the comments field.
func (r *assetResolver) Comments(ctx context.Context, obj *model.Asset, first *int, after *string) (*model1.CommentConnection, error) {
	return r.entityComments(ctx, "asset", obj.ID, first, after)
}

// Evidence is the resolver for the evidence field.
func (r *assetResolver) Evidence(ctx context.Context, obj *model.Asset, first *int, after *string) (*model1.EvidenceConnection, error) {
	return r.entityEvidence(ctx, "asset", obj.ID, first, after)
}

// Dependencies is the resolver for the dependencies field.
func (r *assetResolver) Dependencies(ctx context.Context, obj *model.Asset) ([]*model.Asset, error) {
	var deps []*model.Asset
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		deps, err = r.AssetRepo.GetDependencies(ctx, tx, obj.ID)
		return err
	})
	return deps, err
}

// CreateAsset is the resolver for the createAsset field.
func (r *mutationResolver) CreateAsset(ctx context.Context, input model1.CreateAssetInput) (*model.Asset, error) {
	orgID, ok := auth.OrgIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("authentication required")
	}

	a := &model.Asset{
		OrgID:     orgID,
		Name:      input.Name,
		AssetType: input.AssetType,
		Status:    "in_use",
	}

	if input.Make != nil {
		a.Make = *input.Make
	}
	if input.Model != nil {
		a.Model = *input.Model
	}
	if input.Version != nil {
		a.Version = *input.Version
	}
	a.BusinessOwnerID = input.BusinessOwnerID
	a.TechnicalOwnerID = input.TechnicalOwnerID
	if input.IPAddresses != nil {
		a.IPAddresses = input.IPAddresses
	}
	if input.Hostnames != nil {
		a.Hostnames = input.Hostnames
	}
	if input.Fqdn != nil {
		a.FQDN = *input.Fqdn
	}
	if input.URL != nil {
		a.URL = *input.URL
	}
	if input.LocationSite != nil {
		a.LocationSite = *input.LocationSite
	}
	if input.LocationDetail != nil {
		a.LocationDetail = *input.LocationDetail
	}
	if input.Environment != nil {
		a.Environment = *input.Environment
	}
	if input.Criticality != nil {
		a.Criticality = *input.Criticality
	}
	if input.DataClassification != nil {
		a.DataClassification = *input.DataClassification
	}
	if input.Tags != nil {
		a.Tags = input.Tags
	}

	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		return r.AssetRepo.Create(ctx, tx, a)
	})
	return a, err
}

// UpdateAsset is the resolver for the updateAsset field.
func (r *mutationResolver) UpdateAsset(ctx context.Context, id string, input model1.UpdateAssetInput) (*model.Asset, error) {
	var a *model.Asset
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		a, err = r.AssetRepo.GetByID(ctx, tx, id)
		if err != nil {
			return err
		}
		if input.Name != nil {
			a.Name = *input.Name
		}
		if input.AssetType != nil {
			a.AssetType = *input.AssetType
		}
		if input.Make != nil {
			a.Make = *input.Make
		}
		if input.Model != nil {
			a.Model = *input.Model
		}
		if input.Version != nil {
			a.Version = *input.Version
		}
		if input.BusinessOwnerID != nil {
			a.BusinessOwnerID = input.BusinessOwnerID
		}
		if input.TechnicalOwnerID != nil {
			a.TechnicalOwnerID = input.TechnicalOwnerID
		}
		if input.IPAddresses != nil {
			a.IPAddresses = input.IPAddresses
		}
		if input.Hostnames != nil {
			a.Hostnames = input.Hostnames
		}
		if input.Fqdn != nil {
			a.FQDN = *input.Fqdn
		}
		if input.URL != nil {
			a.URL = *input.URL
		}
		if input.LocationSite != nil {
			a.LocationSite = *input.LocationSite
		}
		if input.LocationDetail != nil {
			a.LocationDetail = *input.LocationDetail
		}
		if input.Environment != nil {
			a.Environment = *input.Environment
		}
		if input.Criticality != nil {
			a.Criticality = *input.Criticality
		}
		if input.DataClassification != nil {
			a.DataClassification = *input.DataClassification
		}
		if input.Tags != nil {
			a.Tags = input.Tags
		}
		if input.Status != nil {
			a.Status = *input.Status
		}
		return r.AssetRepo.Update(ctx, tx, a)
	})
	return a, err
}

// DeleteAsset is the resolver for the deleteAsset field.
func (r *mutationResolver) DeleteAsset(ctx context.Context, id string) (bool, error) {
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		return r.AssetRepo.Delete(ctx, tx, id)
	})
	return err == nil, err
}

// Assets is the resolver for the assets field.
func (r *queryResolver) Assets(ctx context.Context, first *int, after *string, filter *model1.AssetFilter) (*model1.AssetConnection, error) {
	params := paginationParams(first, after)

	var repoFilter *repository.AssetFilter
	if filter != nil {
		repoFilter = &repository.AssetFilter{
			AssetType:   filter.AssetType,
			Environment: filter.Environment,
			Criticality: filter.Criticality,
			Status:      filter.Status,
			OwnerID:     filter.OwnerID,
			Search:      filter.Search,
			Tags:        filter.Tags,
		}
	}

	var assets []*model.Asset
	var pr repository.PaginationResult

	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		assets, pr, err = r.AssetRepo.List(ctx, tx, params, repoFilter)
		return err
	})
	if err != nil {
		return nil, err
	}

	edges := make([]*model1.AssetEdge, len(assets))
	for i, a := range assets {
		edges[i] = &model1.AssetEdge{
			Cursor: repository.EncodeCursor(i),
			Node:   a,
		}
	}

	return &model1.AssetConnection{
		Edges:      edges,
		PageInfo:   toPageInfo(pr),
		TotalCount: pr.TotalCount,
	}, nil
}

// Asset is the resolver for the asset field.
func (r *queryResolver) Asset(ctx context.Context, id string) (*model.Asset, error) {
	var a *model.Asset
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		a, err = r.AssetRepo.GetByID(ctx, tx, id)
		return err
	})
	return a, err
}

// Asset returns AssetResolver implementation.
func (r *Resolver) Asset() AssetResolver { return &assetResolver{r} }

type assetResolver struct{ *Resolver }
