package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	pgx "github.com/jackc/pgx/v5"
	"github.com/jmcintyre/secbase/api/internal/auth"
	model1 "github.com/jmcintyre/secbase/api/internal/graph/model"
	"github.com/jmcintyre/secbase/api/internal/model"
	"github.com/jmcintyre/secbase/api/internal/repository"
)

// VulnOverview is the resolver for the vulnOverview field.
func (r *queryResolver) VulnOverview(ctx context.Context) (*model1.VulnOverview, error) {
	panic(fmt.Errorf("not implemented: VulnOverview - vulnOverview"))
}

// RiskPosture is the resolver for the riskPosture field.
func (r *queryResolver) RiskPosture(ctx context.Context) (*model1.RiskPosture, error) {
	panic(fmt.Errorf("not implemented: RiskPosture - riskPosture"))
}

// IncidentStatus is the resolver for the incidentStatus field.
func (r *queryResolver) IncidentStatus(ctx context.Context) (*model1.IncidentStatusSummary, error) {
	panic(fmt.Errorf("not implemented: IncidentStatus - incidentStatus"))
}

// ComplianceSnapshot is the resolver for the complianceSnapshot field.
func (r *queryResolver) ComplianceSnapshot(ctx context.Context) (*model1.ComplianceSnapshot, error) {
	panic(fmt.Errorf("not implemented: ComplianceSnapshot - complianceSnapshot"))
}

// DrReadiness is the resolver for the drReadiness field.
func (r *queryResolver) DrReadiness(ctx context.Context) (*model1.DrReadiness, error) {
	panic(fmt.Errorf("not implemented: DrReadiness - drReadiness"))
}

// MyTasks is the resolver for the myTasks field.
func (r *queryResolver) MyTasks(ctx context.Context) (*model1.MyTasks, error) {
	panic(fmt.Errorf("not implemented: MyTasks - myTasks"))
}

// CveFeed is the resolver for the cveFeed field.
func (r *queryResolver) CveFeed(ctx context.Context, limit *int) ([]*model.CveFeedEntry, error) {
	panic(fmt.Errorf("not implemented: CveFeed - cveFeed"))
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *Resolver) VulnOverview(ctx context.Context) (*repository.VulnOverview, error) {
	var o *repository.VulnOverview
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		o, err = r.DashboardRepo.GetVulnOverview(ctx, tx)
		return err
	})
	return o, err
}
func (r *Resolver) IncidentStatusSummary(ctx context.Context) (*repository.IncidentSummary, error) {
	var s *repository.IncidentSummary
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		s, err = r.DashboardRepo.GetIncidentSummary(ctx, tx)
		return err
	})
	return s, err
}
func (r *Resolver) DrReadiness(ctx context.Context) (*repository.DrReadiness, error) {
	var d *repository.DrReadiness
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		d, err = r.DashboardRepo.GetDrReadiness(ctx, tx)
		return err
	})
	return d, err
}
func (r *Resolver) MyTasks(ctx context.Context) (*repository.MyTasks, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return &repository.MyTasks{}, nil
	}
	var t *repository.MyTasks
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		t, err = r.DashboardRepo.GetMyTasks(ctx, tx, userID)
		return err
	})
	return t, err
}
func (r *Resolver) CveFeed(ctx context.Context, limit *int) ([]*model.CveFeedEntry, error) {
	n := 20
	if limit != nil && *limit > 0 {
		n = *limit
	}
	var entries []*model.CveFeedEntry
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		entries, err = r.DashboardRepo.ListCveFeed(ctx, tx, n)
		return err
	})
	return entries, err
}
