package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	pgx "github.com/jackc/pgx/v5"
	"github.com/jmcintyre/secbase/api/internal/auth"
	model1 "github.com/jmcintyre/secbase/api/internal/graph/model"
	"github.com/jmcintyre/secbase/api/internal/model"
	"github.com/jmcintyre/secbase/api/internal/repository"
)

// VulnOverview is the resolver for the vulnOverview field.
func (r *queryResolver) VulnOverview(ctx context.Context) (*model1.VulnOverview, error) {
	var o *repository.VulnOverview
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		o, err = r.DashboardRepo.GetVulnOverview(ctx, tx)
		return err
	})
	if err != nil {
		return nil, err
	}
	return &model1.VulnOverview{
		TotalOpen:     o.TotalOpen,
		CriticalCount: o.CriticalCount,
		HighCount:     o.HighCount,
		MediumCount:   o.MediumCount,
		LowCount:      o.LowCount,
	}, nil
}

// RiskPosture is the resolver for the riskPosture field.
func (r *queryResolver) RiskPosture(ctx context.Context) (*model1.RiskPosture, error) {
	var cells []repository.HeatmapCell
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		cells, err = r.RiskRepo.GetHeatmapData(ctx, tx)
		return err
	})
	if err != nil {
		return nil, err
	}

	heatmap := make([]*model1.HeatmapCell, len(cells))
	for i, c := range cells {
		heatmap[i] = &model1.HeatmapCell{
			Likelihood: c.Likelihood,
			Impact:     c.Impact,
			Count:      c.Count,
		}
	}
	return &model1.RiskPosture{
		CountsByLevel: []*model1.LevelCount{},
		HeatmapData:   heatmap,
	}, nil
}

// IncidentStatus is the resolver for the incidentStatus field.
func (r *queryResolver) IncidentStatus(ctx context.Context) (*model1.IncidentStatusSummary, error) {
	var s *repository.IncidentSummary
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		s, err = r.DashboardRepo.GetIncidentSummary(ctx, tx)
		return err
	})
	if err != nil {
		return nil, err
	}
	return &model1.IncidentStatusSummary{
		OpenByImpact:   []*model1.ImpactCount{},
		SLABreaches:    s.SLABreaches,
		RecentTimeline: []*model1.IncidentTimelineEntry{},
	}, nil
}

// ComplianceSnapshot is the resolver for the complianceSnapshot field.
func (r *queryResolver) ComplianceSnapshot(ctx context.Context) (*model1.ComplianceSnapshot, error) {
	var s *repository.ComplianceSummary
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		s, err = r.IsoControlRepo.GetComplianceSummary(ctx, tx)
		return err
	})
	if err != nil {
		return nil, err
	}
	total := float64(s.Implemented + s.PartiallyImplemented + s.NotImplemented + s.NotApplicable)
	if total == 0 {
		return &model1.ComplianceSnapshot{TopGaps: []*model1.ControlGap{}}, nil
	}
	return &model1.ComplianceSnapshot{
		ImplementedPct:          float64(s.Implemented) / total * 100,
		PartiallyImplementedPct: float64(s.PartiallyImplemented) / total * 100,
		NotImplementedPct:       float64(s.NotImplemented) / total * 100,
		NotApplicablePct:        float64(s.NotApplicable) / total * 100,
		TopGaps:                 []*model1.ControlGap{},
	}, nil
}

// DrReadiness is the resolver for the drReadiness field.
func (r *queryResolver) DrReadiness(ctx context.Context) (*model1.DrReadiness, error) {
	var d *repository.DrReadiness
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		d, err = r.DashboardRepo.GetDrReadiness(ctx, tx)
		return err
	})
	if err != nil {
		return nil, err
	}
	var lastResult *string
	if d.LastTestResult != "" {
		lastResult = &d.LastTestResult
	}
	return &model1.DrReadiness{
		NextTestDate:   d.NextTestDate,
		LastTestDate:   d.LastTestDate,
		LastTestResult: lastResult,
	}, nil
}

// MyTasks is the resolver for the myTasks field.
func (r *queryResolver) MyTasks(ctx context.Context) (*model1.MyTasks, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return &model1.MyTasks{}, nil
	}
	var t *repository.MyTasks
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		t, err = r.DashboardRepo.GetMyTasks(ctx, tx, userID)
		return err
	})
	if err != nil {
		return nil, err
	}
	return &model1.MyTasks{
		AssignedVulnCount:     t.Vulnerabilities,
		AssignedRiskCount:     t.Risks,
		AssignedIncidentCount: t.Incidents,
		AssignedActionCount:   t.Actions,
	}, nil
}

// CveFeed is the resolver for the cveFeed field.
func (r *queryResolver) CveFeed(ctx context.Context, limit *int) ([]*model.CveFeedEntry, error) {
	n := 20
	if limit != nil && *limit > 0 {
		n = *limit
	}
	var entries []*model.CveFeedEntry
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		entries, err = r.DashboardRepo.ListCveFeed(ctx, tx, n)
		return err
	})
	return entries, err
}
