package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	pgx "github.com/jackc/pgx/v5"
	"github.com/jmcintyre/secbase/api/internal/auth"
	model1 "github.com/jmcintyre/secbase/api/internal/graph/model"
	"github.com/jmcintyre/secbase/api/internal/model"
	"github.com/jmcintyre/secbase/api/internal/repository"
)

// Reporter is the resolver for the reporter field.
func (r *incidentResolver) Reporter(ctx context.Context, obj *model.Incident) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Reporter - reporter"))
}

// Owner is the resolver for the owner field.
func (r *incidentResolver) Owner(ctx context.Context, obj *model.Incident) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Owner - owner"))
}

// Assets is the resolver for the assets field.
func (r *incidentResolver) Assets(ctx context.Context, obj *model.Incident, first *int, after *string) (*model1.AssetConnection, error) {
	panic(fmt.Errorf("not implemented: Assets - assets"))
}

// Vulnerabilities is the resolver for the vulnerabilities field.
func (r *incidentResolver) Vulnerabilities(ctx context.Context, obj *model.Incident, first *int, after *string) (*model1.VulnerabilityConnection, error) {
	panic(fmt.Errorf("not implemented: Vulnerabilities - vulnerabilities"))
}

// Actions is the resolver for the actions field.
func (r *incidentResolver) Actions(ctx context.Context, obj *model.Incident) ([]*model.IncidentAction, error) {
	panic(fmt.Errorf("not implemented: Actions - actions"))
}

// Comments is the resolver for the comments field.
func (r *incidentResolver) Comments(ctx context.Context, obj *model.Incident, first *int, after *string) (*model1.CommentConnection, error) {
	panic(fmt.Errorf("not implemented: Comments - comments"))
}

// Evidence is the resolver for the evidence field.
func (r *incidentResolver) Evidence(ctx context.Context, obj *model.Incident, first *int, after *string) (*model1.EvidenceConnection, error) {
	panic(fmt.Errorf("not implemented: Evidence - evidence"))
}

// Owner is the resolver for the owner field.
func (r *incidentActionResolver) Owner(ctx context.Context, obj *model.IncidentAction) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Owner - owner"))
}

// CreateIncident is the resolver for the createIncident field.
func (r *mutationResolver) CreateIncident(ctx context.Context, input model1.CreateIncidentInput) (*model.Incident, error) {
	panic(fmt.Errorf("not implemented: CreateIncident - createIncident"))
}

// UpdateIncident is the resolver for the updateIncident field.
func (r *mutationResolver) UpdateIncident(ctx context.Context, id string, input model1.UpdateIncidentInput) (*model.Incident, error) {
	panic(fmt.Errorf("not implemented: UpdateIncident - updateIncident"))
}

// DeleteIncident is the resolver for the deleteIncident field.
func (r *mutationResolver) DeleteIncident(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteIncident - deleteIncident"))
}

// AddIncidentAction is the resolver for the addIncidentAction field.
func (r *mutationResolver) AddIncidentAction(ctx context.Context, incidentID string, input model1.AddIncidentActionInput) (*model.IncidentAction, error) {
	panic(fmt.Errorf("not implemented: AddIncidentAction - addIncidentAction"))
}

// UpdateIncidentAction is the resolver for the updateIncidentAction field.
func (r *mutationResolver) UpdateIncidentAction(ctx context.Context, id string, input model1.UpdateIncidentActionInput) (*model.IncidentAction, error) {
	panic(fmt.Errorf("not implemented: UpdateIncidentAction - updateIncidentAction"))
}

// Incidents is the resolver for the incidents field.
func (r *queryResolver) Incidents(ctx context.Context, first *int, after *string, filter *model1.IncidentFilter) (*model1.IncidentConnection, error) {
	panic(fmt.Errorf("not implemented: Incidents - incidents"))
}

// Incident is the resolver for the incident field.
func (r *queryResolver) Incident(ctx context.Context, id string) (*model.Incident, error) {
	panic(fmt.Errorf("not implemented: Incident - incident"))
}

// Incident returns IncidentResolver implementation.
func (r *Resolver) Incident() IncidentResolver { return &incidentResolver{r} }

// IncidentAction returns IncidentActionResolver implementation.
func (r *Resolver) IncidentAction() IncidentActionResolver { return &incidentActionResolver{r} }

type incidentResolver struct{ *Resolver }
type incidentActionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
type IncidentConnection struct {
	Edges      []*IncidentEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}
type IncidentEdge struct {
	Cursor string          `json:"cursor"`
	Node   *model.Incident `json:"node"`
}

func (r *Resolver) Incidents(ctx context.Context, first *int, after *string, filter *repository.IncidentFilter) (*IncidentConnection, error) {
	params := paginationParams(first, after)
	var incidents []*model.Incident
	var pr repository.PaginationResult

	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		incidents, pr, err = r.IncidentRepo.List(ctx, tx, params, filter)
		return err
	})
	if err != nil {
		return nil, err
	}

	edges := make([]*IncidentEdge, len(incidents))
	for i, inc := range incidents {
		edges[i] = &IncidentEdge{Cursor: repository.EncodeCursor(i), Node: inc}
	}
	return &IncidentConnection{Edges: edges, PageInfo: toPageInfo(pr), TotalCount: pr.TotalCount}, nil
}
func (r *Resolver) CreateIncident(ctx context.Context, input CreateIncidentInput) (*model.Incident, error) {
	orgID, ok := auth.OrgIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("authentication required")
	}

	reporterID, _ := auth.UserIDFromContext(ctx)

	inc := &model.Incident{
		OrgID:            orgID,
		Name:             input.Name,
		Area:             derefStr(input.Area),
		Description:      derefStr(input.Description),
		ImpactSummary:    derefStr(input.ImpactSummary),
		ImpactRating:     derefStr(input.ImpactRating),
		RegulatoryBreach: input.RegulatoryBreach != nil && *input.RegulatoryBreach,
		ReporterID:       &reporterID,
		OwnerID:          input.OwnerID,
		Status:           "new",
	}
	if input.Classification != nil {
		inc.Classification = input.Classification
	}

	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		return r.IncidentRepo.Create(ctx, tx, inc)
	})
	return inc, err
}
func (r *Resolver) UpdateIncident(ctx context.Context, id string, input UpdateIncidentInput) (*model.Incident, error) {
	var inc *model.Incident
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		inc, err = r.IncidentRepo.GetByID(ctx, tx, id)
		if err != nil {
			return err
		}
		if input.Name != nil {
			inc.Name = *input.Name
		}
		if input.Area != nil {
			inc.Area = *input.Area
		}
		if input.Description != nil {
			inc.Description = *input.Description
		}
		if input.ImpactSummary != nil {
			inc.ImpactSummary = *input.ImpactSummary
		}
		if input.ImpactRating != nil {
			inc.ImpactRating = *input.ImpactRating
		}
		if input.Classification != nil {
			inc.Classification = input.Classification
		}
		if input.Status != nil {
			inc.Status = *input.Status
		}
		if input.RootCause != nil {
			inc.RootCause = *input.RootCause
		}
		if input.RootCauseCategory != nil {
			inc.RootCauseCategory = *input.RootCauseCategory
		}
		if input.OwnerID != nil {
			inc.OwnerID = input.OwnerID
		}
		return r.IncidentRepo.Update(ctx, tx, inc)
	})
	return inc, err
}
func (r *Resolver) DeleteIncident(ctx context.Context, id string) (bool, error) {
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		return r.IncidentRepo.Delete(ctx, tx, id)
	})
	return err == nil, err
}
func (r *Resolver) CreateIncidentAction(ctx context.Context, incidentID string, input CreateActionInput) (*model.IncidentAction, error) {
	a := &model.IncidentAction{
		IncidentID:  incidentID,
		ActionType:  input.ActionType,
		Description: input.Description,
		OwnerID:     input.OwnerID,
		Status:      "open",
	}

	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		return r.IncidentRepo.CreateAction(ctx, tx, a)
	})
	return a, err
}
func (r *Resolver) UpdateIncidentAction(ctx context.Context, id string, input UpdateActionInput) (*model.IncidentAction, error) {
	// For simplicity, load directly
	a := &model.IncidentAction{ID: id}
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		if input.Description != nil {
			a.Description = *input.Description
		}
		if input.OwnerID != nil {
			a.OwnerID = input.OwnerID
		}
		if input.Status != nil {
			a.Status = *input.Status
		}
		return r.IncidentRepo.UpdateAction(ctx, tx, a)
	})
	return a, err
}
func (r *Resolver) IncidentActions(ctx context.Context, inc *model.Incident) ([]*model.IncidentAction, error) {
	var actions []*model.IncidentAction
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		actions, err = r.IncidentRepo.ListActions(ctx, tx, inc.ID)
		return err
	})
	return actions, err
}
func (r *Resolver) IncidentOwner(ctx context.Context, inc *model.Incident) (*model.User, error) {
	if inc.OwnerID == nil {
		return nil, nil
	}
	return r.resolveUser(ctx, *inc.OwnerID)
}
func (r *Resolver) IncidentReporter(ctx context.Context, inc *model.Incident) (*model.User, error) {
	if inc.ReporterID == nil {
		return nil, nil
	}
	return r.resolveUser(ctx, *inc.ReporterID)
}

type CreateIncidentInput struct {
	Name             string   `json:"name"`
	Area             *string  `json:"area"`
	Description      *string  `json:"description"`
	ImpactSummary    *string  `json:"impactSummary"`
	ImpactRating     *string  `json:"impactRating"`
	Classification   []string `json:"classification"`
	RegulatoryBreach *bool    `json:"regulatoryBreach"`
	OwnerID          *string  `json:"ownerId"`
}
type UpdateIncidentInput struct {
	Name              *string  `json:"name"`
	Area              *string  `json:"area"`
	Description       *string  `json:"description"`
	ImpactSummary     *string  `json:"impactSummary"`
	ImpactRating      *string  `json:"impactRating"`
	Classification    []string `json:"classification"`
	Status            *string  `json:"status"`
	RootCause         *string  `json:"rootCause"`
	RootCauseCategory *string  `json:"rootCauseCategory"`
	OwnerID           *string  `json:"ownerId"`
}
type CreateActionInput struct {
	ActionType  string  `json:"actionType"`
	Description string  `json:"description"`
	OwnerID     *string `json:"ownerId"`
}
type UpdateActionInput struct {
	Description *string `json:"description"`
	OwnerID     *string `json:"ownerId"`
	Status      *string `json:"status"`
}
