package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	pgx "github.com/jackc/pgx/v5"
	model1 "github.com/jmcintyre/secbase/api/internal/graph/model"
	"github.com/jmcintyre/secbase/api/internal/model"
	"github.com/jmcintyre/secbase/api/internal/repository"
)

// UpdateOrgIsoControl is the resolver for the updateOrgIsoControl field.
func (r *mutationResolver) UpdateOrgIsoControl(ctx context.Context, id string, input model1.UpdateOrgIsoControlInput) (*model.OrgIsoControl, error) {
	var oc *model.OrgIsoControl
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		oc, err = r.IsoControlRepo.GetOrgControl(ctx, tx, id)
		if err != nil {
			existing, upsertErr := r.IsoControlRepo.GetOrgControlByIsoControlID(ctx, tx, id)
			if upsertErr != nil {
				oc = &model.OrgIsoControl{IsoControlID: id}
			} else {
				oc = existing
			}
		}

		if input.Applicability != nil {
			oc.Applicability = *input.Applicability
		}
		if input.NonApplicabilityJustification != nil {
			oc.NonApplicabilityJustification = *input.NonApplicabilityJustification
		}
		if input.ImplementationStatus != nil {
			oc.ImplementationStatus = *input.ImplementationStatus
		}
		if input.ImplementationDescription != nil {
			oc.ImplementationDescription = *input.ImplementationDescription
		}
		if input.ResponsibleOwnerID != nil {
			oc.ResponsibleOwnerID = input.ResponsibleOwnerID
		}

		return r.IsoControlRepo.UpsertOrgControl(ctx, tx, oc)
	})
	return oc, err
}

// Control is the resolver for the control field.
func (r *orgIsoControlResolver) Control(ctx context.Context, obj *model.OrgIsoControl) (*model.IsoControl, error) {
	var c *model.IsoControl
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		c, err = r.IsoControlRepo.GetByID(ctx, tx, obj.IsoControlID)
		return err
	})
	return c, err
}

// ResponsibleOwner is the resolver for the responsibleOwner field.
func (r *orgIsoControlResolver) ResponsibleOwner(ctx context.Context, obj *model.OrgIsoControl) (*model.User, error) {
	if obj.ResponsibleOwnerID == nil {
		return nil, nil
	}
	return r.resolveUser(ctx, *obj.ResponsibleOwnerID)
}

// Assets is the resolver for the assets field.
func (r *orgIsoControlResolver) Assets(ctx context.Context, obj *model.OrgIsoControl, first *int, after *string) (*model1.AssetConnection, error) {
	return &model1.AssetConnection{Edges: []*model1.AssetEdge{}, PageInfo: &model1.PageInfo{}, TotalCount: 0}, nil
}

// Risks is the resolver for the risks field.
func (r *orgIsoControlResolver) Risks(ctx context.Context, obj *model.OrgIsoControl, first *int, after *string) (*model1.RiskConnection, error) {
	return &model1.RiskConnection{Edges: []*model1.RiskEdge{}, PageInfo: &model1.PageInfo{}, TotalCount: 0}, nil
}

// Comments is the resolver for the comments field.
func (r *orgIsoControlResolver) Comments(ctx context.Context, obj *model.OrgIsoControl, first *int, after *string) (*model1.CommentConnection, error) {
	return r.entityComments(ctx, "org_iso_control", obj.ID, first, after)
}

// Evidence is the resolver for the evidence field.
func (r *orgIsoControlResolver) Evidence(ctx context.Context, obj *model.OrgIsoControl, first *int, after *string) (*model1.EvidenceConnection, error) {
	return r.entityEvidence(ctx, "org_iso_control", obj.ID, first, after)
}

// IsoControls is the resolver for the isoControls field.
func (r *queryResolver) IsoControls(ctx context.Context, theme *string) ([]*model.IsoControl, error) {
	var controls []*model.IsoControl
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		controls, err = r.IsoControlRepo.ListControls(ctx, tx, theme)
		return err
	})
	return controls, err
}

// OrgIsoControls is the resolver for the orgIsoControls field.
func (r *queryResolver) OrgIsoControls(ctx context.Context, first *int, after *string, filter *model1.OrgIsoControlFilter) (*model1.OrgIsoControlConnection, error) {
	params := paginationParams(first, after)
	var repoFilter *repository.IsoFilter
	if filter != nil {
		repoFilter = &repository.IsoFilter{
			ImplementationStatus: filter.ImplementationStatus,
			Theme:                filter.Theme,
			Search:               filter.Search,
		}
	}

	var controls []*model.OrgIsoControl
	var pr repository.PaginationResult

	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		controls, pr, err = r.IsoControlRepo.ListOrgControls(ctx, tx, params, repoFilter)
		return err
	})
	if err != nil {
		return nil, err
	}

	edges := make([]*model1.OrgIsoControlEdge, len(controls))
	for i, c := range controls {
		edges[i] = &model1.OrgIsoControlEdge{Cursor: repository.EncodeCursor(i), Node: c}
	}
	return &model1.OrgIsoControlConnection{Edges: edges, PageInfo: toPageInfo(pr), TotalCount: pr.TotalCount}, nil
}

// OrgIsoControl is the resolver for the orgIsoControl field.
func (r *queryResolver) OrgIsoControl(ctx context.Context, id string) (*model.OrgIsoControl, error) {
	var oc *model.OrgIsoControl
	err := r.DB.WithTx(ctx, func(tx pgx.Tx) error {
		var err error
		oc, err = r.IsoControlRepo.GetOrgControl(ctx, tx, id)
		return err
	})
	return oc, err
}

// OrgIsoControl returns OrgIsoControlResolver implementation.
func (r *Resolver) OrgIsoControl() OrgIsoControlResolver { return &orgIsoControlResolver{r} }

type orgIsoControlResolver struct{ *Resolver }
