// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/jmcintyre/secbase/api/internal/model"
)

type AddCommentInput struct {
	EntityType string `json:"entityType"`
	EntityID   string `json:"entityId"`
	Body       string `json:"body"`
}

type AddEvidenceInput struct {
	EntityType  string `json:"entityType"`
	EntityID    string `json:"entityId"`
	FileName    string `json:"fileName"`
	FileSize    int    `json:"fileSize"`
	ContentType string `json:"contentType"`
}

type AddIncidentActionInput struct {
	ActionType  string     `json:"actionType"`
	Description string     `json:"description"`
	OwnerID     *string    `json:"ownerId,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
}

type AddRiskTreatmentInput struct {
	Action        string     `json:"action"`
	ResponsibleID *string    `json:"responsibleId,omitempty"`
	Deadline      *time.Time `json:"deadline,omitempty"`
}

type AssetConnection struct {
	Edges      []*AssetEdge `json:"edges"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

type AssetEdge struct {
	Cursor string       `json:"cursor"`
	Node   *model.Asset `json:"node"`
}

type AssetFilter struct {
	AssetType   *string  `json:"assetType,omitempty"`
	Environment *string  `json:"environment,omitempty"`
	Criticality *int     `json:"criticality,omitempty"`
	Status      *string  `json:"status,omitempty"`
	OwnerID     *string  `json:"ownerId,omitempty"`
	Search      *string  `json:"search,omitempty"`
	Tags        []string `json:"tags,omitempty"`
}

type AssetVulnCount struct {
	Asset *model.Asset `json:"asset"`
	Count int          `json:"count"`
}

type AuthPayload struct {
	AccessToken  string      `json:"accessToken"`
	RefreshToken string      `json:"refreshToken"`
	User         *model.User `json:"user"`
}

type BulkVulnUpdateInput struct {
	Status  *string  `json:"status,omitempty"`
	OwnerID *string  `json:"ownerId,omitempty"`
	Tags    []string `json:"tags,omitempty"`
}

type CommentConnection struct {
	Edges      []*CommentEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

type CommentEdge struct {
	Cursor string         `json:"cursor"`
	Node   *model.Comment `json:"node"`
}

type ComplianceSnapshot struct {
	ImplementedPct          float64       `json:"implementedPct"`
	PartiallyImplementedPct float64       `json:"partiallyImplementedPct"`
	NotImplementedPct       float64       `json:"notImplementedPct"`
	NotApplicablePct        float64       `json:"notApplicablePct"`
	TopGaps                 []*ControlGap `json:"topGaps"`
}

type ControlGap struct {
	Control *model.IsoControl `json:"control"`
	Status  string            `json:"status"`
}

type CreateAssetInput struct {
	Name               string   `json:"name"`
	AssetType          string   `json:"assetType"`
	Make               *string  `json:"make,omitempty"`
	Model              *string  `json:"model,omitempty"`
	Version            *string  `json:"version,omitempty"`
	BusinessOwnerID    *string  `json:"businessOwnerId,omitempty"`
	TechnicalOwnerID   *string  `json:"technicalOwnerId,omitempty"`
	IPAddresses        []string `json:"ipAddresses,omitempty"`
	Hostnames          []string `json:"hostnames,omitempty"`
	Fqdn               *string  `json:"fqdn,omitempty"`
	URL                *string  `json:"url,omitempty"`
	LocationSite       *string  `json:"locationSite,omitempty"`
	LocationDetail     *string  `json:"locationDetail,omitempty"`
	Environment        *string  `json:"environment,omitempty"`
	Criticality        *int     `json:"criticality,omitempty"`
	DataClassification *string  `json:"dataClassification,omitempty"`
	Tags               []string `json:"tags,omitempty"`
}

type CreateDrPlanInput struct {
	Name       string   `json:"name"`
	Scope      *string  `json:"scope,omitempty"`
	OwnerID    *string  `json:"ownerId,omitempty"`
	Version    *string  `json:"version,omitempty"`
	RtoMinutes *int     `json:"rtoMinutes,omitempty"`
	RpoMinutes *int     `json:"rpoMinutes,omitempty"`
	Playbook   *string  `json:"playbook,omitempty"`
	AssetIds   []string `json:"assetIds,omitempty"`
}

type CreateGroupInput struct {
	Name        string   `json:"name"`
	Description *string  `json:"description,omitempty"`
	Permissions []string `json:"permissions"`
}

type CreateIncidentInput struct {
	Name             string     `json:"name"`
	Area             *string    `json:"area,omitempty"`
	Description      *string    `json:"description,omitempty"`
	ImpactSummary    *string    `json:"impactSummary,omitempty"`
	ImpactRating     *string    `json:"impactRating,omitempty"`
	Classification   []string   `json:"classification,omitempty"`
	RegulatoryBreach *bool      `json:"regulatoryBreach,omitempty"`
	ReporterID       *string    `json:"reporterId,omitempty"`
	OwnerID          *string    `json:"ownerId,omitempty"`
	DetectedAt       *time.Time `json:"detectedAt,omitempty"`
	SLADeadline      *time.Time `json:"slaDeadline,omitempty"`
	AssetIds         []string   `json:"assetIds,omitempty"`
	VulnerabilityIds []string   `json:"vulnerabilityIds,omitempty"`
}

type CreateRiskInput struct {
	Title              string     `json:"title"`
	Description        *string    `json:"description,omitempty"`
	Scenario           *string    `json:"scenario,omitempty"`
	Category           *string    `json:"category,omitempty"`
	Source             *string    `json:"source,omitempty"`
	InherentLikelihood *int       `json:"inherentLikelihood,omitempty"`
	InherentImpact     *int       `json:"inherentImpact,omitempty"`
	ResidualLikelihood *int       `json:"residualLikelihood,omitempty"`
	ResidualImpact     *int       `json:"residualImpact,omitempty"`
	OwnerID            *string    `json:"ownerId,omitempty"`
	ApproverID         *string    `json:"approverId,omitempty"`
	ReviewDate         *time.Time `json:"reviewDate,omitempty"`
	AssetIds           []string   `json:"assetIds,omitempty"`
	ControlIds         []string   `json:"controlIds,omitempty"`
}

type CreateUserInput struct {
	Email       string   `json:"email"`
	Password    string   `json:"password"`
	DisplayName string   `json:"displayName"`
	JobTitle    *string  `json:"jobTitle,omitempty"`
	Department  *string  `json:"department,omitempty"`
	GroupIds    []string `json:"groupIds,omitempty"`
}

type CreateVulnerabilityInput struct {
	Title         string     `json:"title"`
	Description   *string    `json:"description,omitempty"`
	Source        *string    `json:"source,omitempty"`
	CveIds        []string   `json:"cveIds,omitempty"`
	CvssScore     *float64   `json:"cvssScore,omitempty"`
	CvssVector    *string    `json:"cvssVector,omitempty"`
	Severity      *string    `json:"severity,omitempty"`
	DiscoveryDate *time.Time `json:"discoveryDate,omitempty"`
	DueDate       *time.Time `json:"dueDate,omitempty"`
	OwnerID       *string    `json:"ownerId,omitempty"`
	AnalystID     *string    `json:"analystId,omitempty"`
	Tags          []string   `json:"tags,omitempty"`
	Notes         *string    `json:"notes,omitempty"`
	AssetIds      []string   `json:"assetIds,omitempty"`
}

type CveCount struct {
	CveID    string  `json:"cveId"`
	Count    int     `json:"count"`
	Severity *string `json:"severity,omitempty"`
}

type DrPlanConnection struct {
	Edges      []*DrPlanEdge `json:"edges"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type DrPlanEdge struct {
	Cursor string        `json:"cursor"`
	Node   *model.DrPlan `json:"node"`
}

type DrPlanFilter struct {
	Status  *string `json:"status,omitempty"`
	OwnerID *string `json:"ownerId,omitempty"`
	Search  *string `json:"search,omitempty"`
}

type DrReadiness struct {
	NextTestDate    *time.Time `json:"nextTestDate,omitempty"`
	LastTestDate    *time.Time `json:"lastTestDate,omitempty"`
	LastTestResult  *string    `json:"lastTestResult,omitempty"`
	PlaybookVersion *string    `json:"playbookVersion,omitempty"`
}

type EvidenceConnection struct {
	Edges      []*EvidenceEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type EvidenceEdge struct {
	Cursor string          `json:"cursor"`
	Node   *model.Evidence `json:"node"`
}

type GroupConnection struct {
	Edges      []*GroupEdge `json:"edges"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

type GroupEdge struct {
	Cursor string       `json:"cursor"`
	Node   *model.Group `json:"node"`
}

type HeatmapCell struct {
	Likelihood int `json:"likelihood"`
	Impact     int `json:"impact"`
	Count      int `json:"count"`
}

type ImpactCount struct {
	Impact string `json:"impact"`
	Count  int    `json:"count"`
}

type IncidentConnection struct {
	Edges      []*IncidentEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type IncidentEdge struct {
	Cursor string          `json:"cursor"`
	Node   *model.Incident `json:"node"`
}

type IncidentFilter struct {
	ImpactRating *string    `json:"impactRating,omitempty"`
	Status       *string    `json:"status,omitempty"`
	OwnerID      *string    `json:"ownerId,omitempty"`
	Search       *string    `json:"search,omitempty"`
	OpenedAfter  *time.Time `json:"openedAfter,omitempty"`
	OpenedBefore *time.Time `json:"openedBefore,omitempty"`
}

type IncidentStatusSummary struct {
	OpenByImpact   []*ImpactCount           `json:"openByImpact"`
	SLABreaches    int                      `json:"slaBreaches"`
	RecentTimeline []*IncidentTimelineEntry `json:"recentTimeline"`
}

type IncidentTimelineEntry struct {
	Incident *model.Incident `json:"incident"`
	Date     time.Time       `json:"date"`
}

type LevelCount struct {
	Level string `json:"level"`
	Count int    `json:"count"`
}

type LoginInput struct {
	Email    string  `json:"email"`
	Password string  `json:"password"`
	TotpCode *string `json:"totpCode,omitempty"`
}

type Mutation struct {
}

type MyTasks struct {
	AssignedVulnCount     int                    `json:"assignedVulnCount"`
	AssignedRiskCount     int                    `json:"assignedRiskCount"`
	AssignedIncidentCount int                    `json:"assignedIncidentCount"`
	AssignedActionCount   int                    `json:"assignedActionCount"`
	RecentVulns           []*model.Vulnerability `json:"recentVulns"`
	RecentRisks           []*model.Risk          `json:"recentRisks"`
	RecentIncidents       []*model.Incident      `json:"recentIncidents"`
}

type OrgIsoControlConnection struct {
	Edges      []*OrgIsoControlEdge `json:"edges"`
	PageInfo   *PageInfo            `json:"pageInfo"`
	TotalCount int                  `json:"totalCount"`
}

type OrgIsoControlEdge struct {
	Cursor string               `json:"cursor"`
	Node   *model.OrgIsoControl `json:"node"`
}

type OrgIsoControlFilter struct {
	Theme                *string `json:"theme,omitempty"`
	ImplementationStatus *string `json:"implementationStatus,omitempty"`
	Applicability        *string `json:"applicability,omitempty"`
	OwnerID              *string `json:"ownerId,omitempty"`
	Search               *string `json:"search,omitempty"`
}

// Relay-compatible page info for cursor-based pagination.
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type RecordDrTestInput struct {
	TestType     string     `json:"testType"`
	PlannedDate  *time.Time `json:"plannedDate,omitempty"`
	ActualDate   *time.Time `json:"actualDate,omitempty"`
	Result       *string    `json:"result,omitempty"`
	Observations *string    `json:"observations,omitempty"`
}

type RiskConnection struct {
	Edges      []*RiskEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type RiskEdge struct {
	Cursor string      `json:"cursor"`
	Node   *model.Risk `json:"node"`
}

type RiskFilter struct {
	Category         *string `json:"category,omitempty"`
	Status           *string `json:"status,omitempty"`
	OwnerID          *string `json:"ownerId,omitempty"`
	MinInherentLevel *int    `json:"minInherentLevel,omitempty"`
	Search           *string `json:"search,omitempty"`
}

type RiskPosture struct {
	CountsByLevel []*LevelCount  `json:"countsByLevel"`
	HeatmapData   []*HeatmapCell `json:"heatmapData"`
}

type TotpSetupPayload struct {
	Secret          string   `json:"secret"`
	ProvisioningURL string   `json:"provisioningUrl"`
	BackupCodes     []string `json:"backupCodes"`
}

type TotpVerifyPayload struct {
	Success bool `json:"success"`
}

type UpdateAssetInput struct {
	Name               *string  `json:"name,omitempty"`
	AssetType          *string  `json:"assetType,omitempty"`
	Make               *string  `json:"make,omitempty"`
	Model              *string  `json:"model,omitempty"`
	Version            *string  `json:"version,omitempty"`
	BusinessOwnerID    *string  `json:"businessOwnerId,omitempty"`
	TechnicalOwnerID   *string  `json:"technicalOwnerId,omitempty"`
	IPAddresses        []string `json:"ipAddresses,omitempty"`
	Hostnames          []string `json:"hostnames,omitempty"`
	Fqdn               *string  `json:"fqdn,omitempty"`
	URL                *string  `json:"url,omitempty"`
	LocationSite       *string  `json:"locationSite,omitempty"`
	LocationDetail     *string  `json:"locationDetail,omitempty"`
	Environment        *string  `json:"environment,omitempty"`
	Criticality        *int     `json:"criticality,omitempty"`
	DataClassification *string  `json:"dataClassification,omitempty"`
	Tags               []string `json:"tags,omitempty"`
	Status             *string  `json:"status,omitempty"`
}

type UpdateDrPlanInput struct {
	Name       *string `json:"name,omitempty"`
	Scope      *string `json:"scope,omitempty"`
	OwnerID    *string `json:"ownerId,omitempty"`
	Version    *string `json:"version,omitempty"`
	RtoMinutes *int    `json:"rtoMinutes,omitempty"`
	RpoMinutes *int    `json:"rpoMinutes,omitempty"`
	Playbook   *string `json:"playbook,omitempty"`
	Status     *string `json:"status,omitempty"`
}

type UpdateDrTestInput struct {
	ActualDate   *time.Time `json:"actualDate,omitempty"`
	Result       *string    `json:"result,omitempty"`
	Observations *string    `json:"observations,omitempty"`
}

type UpdateGroupInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
}

type UpdateIncidentActionInput struct {
	Description *string    `json:"description,omitempty"`
	OwnerID     *string    `json:"ownerId,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
	Status      *string    `json:"status,omitempty"`
}

type UpdateIncidentInput struct {
	Name              *string    `json:"name,omitempty"`
	Area              *string    `json:"area,omitempty"`
	Description       *string    `json:"description,omitempty"`
	ImpactSummary     *string    `json:"impactSummary,omitempty"`
	ImpactRating      *string    `json:"impactRating,omitempty"`
	Classification    []string   `json:"classification,omitempty"`
	RegulatoryBreach  *bool      `json:"regulatoryBreach,omitempty"`
	OwnerID           *string    `json:"ownerId,omitempty"`
	Status            *string    `json:"status,omitempty"`
	RootCause         *string    `json:"rootCause,omitempty"`
	RootCauseCategory *string    `json:"rootCauseCategory,omitempty"`
	CorrectiveActions *string    `json:"correctiveActions,omitempty"`
	PreventiveActions *string    `json:"preventiveActions,omitempty"`
	ContainedAt       *time.Time `json:"containedAt,omitempty"`
	ResolvedAt        *time.Time `json:"resolvedAt,omitempty"`
	ClosedAt          *time.Time `json:"closedAt,omitempty"`
}

type UpdateOrgIsoControlInput struct {
	Applicability                 *string `json:"applicability,omitempty"`
	NonApplicabilityJustification *string `json:"nonApplicabilityJustification,omitempty"`
	ImplementationStatus          *string `json:"implementationStatus,omitempty"`
	ImplementationDescription     *string `json:"implementationDescription,omitempty"`
	ResponsibleOwnerID            *string `json:"responsibleOwnerId,omitempty"`
}

type UpdateProfileInput struct {
	DisplayName       *string `json:"displayName,omitempty"`
	JobTitle          *string `json:"jobTitle,omitempty"`
	Department        *string `json:"department,omitempty"`
	ProfilePictureURL *string `json:"profilePictureUrl,omitempty"`
}

type UpdateRiskInput struct {
	Title              *string    `json:"title,omitempty"`
	Description        *string    `json:"description,omitempty"`
	Scenario           *string    `json:"scenario,omitempty"`
	Category           *string    `json:"category,omitempty"`
	Source             *string    `json:"source,omitempty"`
	InherentLikelihood *int       `json:"inherentLikelihood,omitempty"`
	InherentImpact     *int       `json:"inherentImpact,omitempty"`
	ResidualLikelihood *int       `json:"residualLikelihood,omitempty"`
	ResidualImpact     *int       `json:"residualImpact,omitempty"`
	Status             *string    `json:"status,omitempty"`
	OwnerID            *string    `json:"ownerId,omitempty"`
	ApproverID         *string    `json:"approverId,omitempty"`
	ReviewDate         *time.Time `json:"reviewDate,omitempty"`
}

type UpdateRiskMatrixConfigInput struct {
	LikelihoodLabels []string `json:"likelihoodLabels"`
	ImpactLabels     []string `json:"impactLabels"`
	LevelThresholds  string   `json:"levelThresholds"`
}

type UpdateRiskTreatmentInput struct {
	Action        *string    `json:"action,omitempty"`
	ResponsibleID *string    `json:"responsibleId,omitempty"`
	Deadline      *time.Time `json:"deadline,omitempty"`
	Status        *string    `json:"status,omitempty"`
}

type UpdateUserInput struct {
	DisplayName *string `json:"displayName,omitempty"`
	JobTitle    *string `json:"jobTitle,omitempty"`
	Department  *string `json:"department,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type UpdateVulnerabilityInput struct {
	Title       *string    `json:"title,omitempty"`
	Description *string    `json:"description,omitempty"`
	Source      *string    `json:"source,omitempty"`
	CveIds      []string   `json:"cveIds,omitempty"`
	CvssScore   *float64   `json:"cvssScore,omitempty"`
	CvssVector  *string    `json:"cvssVector,omitempty"`
	Severity    *string    `json:"severity,omitempty"`
	Status      *string    `json:"status,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
	ClosureDate *time.Time `json:"closureDate,omitempty"`
	OwnerID     *string    `json:"ownerId,omitempty"`
	AnalystID   *string    `json:"analystId,omitempty"`
	ApproverID  *string    `json:"approverId,omitempty"`
	Tags        []string   `json:"tags,omitempty"`
	Notes       *string    `json:"notes,omitempty"`
}

type UserConnection struct {
	Edges      []*UserEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type UserEdge struct {
	Cursor string      `json:"cursor"`
	Node   *model.User `json:"node"`
}

type UserFilter struct {
	Status  *string `json:"status,omitempty"`
	Search  *string `json:"search,omitempty"`
	GroupID *string `json:"groupId,omitempty"`
}

type VulnFilter struct {
	Severity         *string    `json:"severity,omitempty"`
	Status           *string    `json:"status,omitempty"`
	AssetID          *string    `json:"assetId,omitempty"`
	OwnerID          *string    `json:"ownerId,omitempty"`
	CveID            *string    `json:"cveId,omitempty"`
	Tags             []string   `json:"tags,omitempty"`
	Search           *string    `json:"search,omitempty"`
	DiscoveredAfter  *time.Time `json:"discoveredAfter,omitempty"`
	DiscoveredBefore *time.Time `json:"discoveredBefore,omitempty"`
}

// Dashboard aggregate types for widgets.
type VulnOverview struct {
	TotalOpen     int               `json:"totalOpen"`
	CriticalCount int               `json:"criticalCount"`
	HighCount     int               `json:"highCount"`
	MediumCount   int               `json:"mediumCount"`
	LowCount      int               `json:"lowCount"`
	MttrDays      *float64          `json:"mttrDays,omitempty"`
	TopAssets     []*AssetVulnCount `json:"topAssets"`
	TopCves       []*CveCount       `json:"topCves"`
}

type VulnerabilityConnection struct {
	Edges      []*VulnerabilityEdge `json:"edges"`
	PageInfo   *PageInfo            `json:"pageInfo"`
	TotalCount int                  `json:"totalCount"`
}

type VulnerabilityEdge struct {
	Cursor string               `json:"cursor"`
	Node   *model.Vulnerability `json:"node"`
}

type VulnerabilityHistoryConnection struct {
	Edges      []*VulnerabilityHistoryEdge `json:"edges"`
	PageInfo   *PageInfo                   `json:"pageInfo"`
	TotalCount int                         `json:"totalCount"`
}

type VulnerabilityHistoryEdge struct {
	Cursor string                      `json:"cursor"`
	Node   *model.VulnerabilityHistory `json:"node"`
}
